replicaCount: 1
image:
  repository: julioraulcarranzaruiz/python-app
  pullPolicy: IfNotPresent
  tag: b6982b
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: python-app.test.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers
resources: {}
requests:
  cpu: 50m
  memory: 50M
livenessProbe:
  httpGet:
    path: /api/vi/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/vi/healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
